name: "PR Treat Action"
description: "Posts a random image as a recognition on a PR"
author: "parthiv"
branding:
  icon: "gift"
  color: "purple"
inputs:
  github_token:
    description: "GitHub Token for authentication"
    required: true

runs:
  using: "node16" 
  main: "index.js"